### ISSUE TITLE
Setup GSOC Blog

### ISSUE THREAD

**Issue by cannin** [cannin/graph_neural_network_drug_response#1]
I think it is a requirement (correct me if I am wrong) that you document your progress. Please set up a blog: 

https://github.com/cannin/causalpath_cytoscape_app/tree/gh-pages

See the example above from a project last year and reproduce it here with the same template.

**Comment by inoue0426** [comment]
@cannin Hi, I set up the blog.
Please check it.

**Comment by inoue0426** [comment]
Hi @cannin 

I set up the template.
However, the website cannot show the 2022's article though it can show 2021 one.
https://lunean.com/graph_neural_network_drug_response/
Do you know why this is happening?

**Comment by cannin** [comment]
@inoue0426 You should rename the file with 2022 and also change the content (including the author line) here:

https://github.com/cannin/graph_neural_network_drug_response/blob/main/docs/_reports/2021-06-14-gsoc-week-one.md

**Comment by inoue0426** [comment]
@cannin I just changed it but the blog only shows 404.
https://lunean.com/graph_neural_network_drug_response/reports/2022-06-07-gsoc-week-zero.html
Do you know why this happens?

**Comment by inoue0426** [comment]
I don't know but if I set the article name to "2021****" then it can show it but not show the "2022".
https://lunean.com/graph_neural_network_drug_response/reports/2021-06-21-gsoc-week-two.html
https://lunean.com/graph_neural_network_drug_response/reports/2022-06-14-gsoc-week-one.html

**Comment by cannin** [comment]
It looks like it is working. I believe it was that the line below is not a full link and there perhaps, it is invalid Markdown: 

https://github.com/cannin/graph_neural_network_drug_response/blob/9e427cb9e585b7f0adc7ed7dd3dec585aace789e/docs/_posts/2022-06-07-gsoc-week-two.md?plain=1#L36

In previous runs here: https://github.com/cannin/graph_neural_network_drug_response/runs/6748573816?check_suite_focus=true the Build step does not write the some of the HTML files.

**Comment by inoue0426** [comment]
I see. I didn't realize it.
Thank you for your help to fix it!
